#!/usr/bin/env bash
set -euo pipefail

HOST="${1:-asus}"

alejandra .

case "$HOST" in
  asus)
    sudo nixos-rebuild switch --flake .#asus
    ;;
  nuc)
    nixos-rebuild switch --flake .#nuc --target-host cloudgenius@nuc --sudo
    ;;
  all)
    sudo nixos-rebuild switch --flake .#asus
    nixos-rebuild switch --flake .#nuc --target-host cloudgenius@nuc --sudo
    ;;
  *)
    echo "Usage: ./redo [asus|nuc|all]"
    exit 1
    ;;
esac
