foreground #D4D4D4
background #0A0A0A
selection_foreground #D4D4D4
selection_background #3A3A3A
cursor #D4D4D4
url_color #FFFFFF
color0 #171717
color1 #FF5555
color2 #50FA7B
color3 #F1FA8C
color4 #6272A4
color5 #FF79C6
color6 #8BE9FD
color7 #D4D4D4
color8 #3A3A3A
color9 #FF5555
color10 #50FA7B
color11 #F1FA8C
color12 #6272A4
color13 #FF79C6
color14 #8BE9FD
color15 #FFFFFF
